spring.application.name=preferences

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

server.port=8081
spring.jpa.hibernate.ddl-auto=update

#RabbitMQ configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=user